name = "telegram-ai"
main = "src/index.js"
compatibility_date = "2023-10-01"

# AI Binding
[ai]
binding = "AI"

# KV Namespace
[[kv_namespaces]]
binding = "TELEGRAM_KV"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

# Environment variables
[vars]
TELEGRAM_BOT_TOKEN = "your_telegram_bot_token_here"
WEBHOOK_SECRET = "your_webhook_secret_here"
MAX_HISTORY_LENGTH = "10"  # Maksimal riwayat percakapan
